print("Please enter the following information so i can sell it for a profit!")
First_name=input("First name: ")
Last_name=input("Last name: ")
Grade=int(input("Grade: "))
Student_id=int(input("Student id: "))
Login=(input("Login: "))
GPA=float(input("GPA(0.0-4.0): "))
print("Your information:")
print(f"\t Login\t: {Login} \n \t Id\t:{Student_id} \n \t Name\t:{First_name} \n \t GPA\t:{GPA} \n \t Grade\t:{Grade}")
# print(f"     Id:{Student_id}")
# print(f"     Name:{First_name}")
# print(f"     GPA:{GPA}")
# print(f"     Grade:{Grade}")
