name=input("Enter your name:")
age=int(input("Enter your age:"))
DOB=input("Enter your DOB:")
location=input("Enter your location:")
clg_name=input("Enter your college name:")
print("Hello,my name is",name,"I am",age,"years old and was born on",DOB,".Currently,I am located in",location,"and I completed my degree at",clg_name)